[project]
name = "ar-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "lxml>=6.0.2",
    "requests>=2.32.5",
    "tqdm>=4.67.0",
    "sentence-transformers>=3.0",
    "chromadb>=0.5",
    "fastapi>=0.115",
    "uvicorn>=0.34",
    "httpx>=0.28",
    "gradio>=4.44",
]
